apiVersion: v1
kind: Pod
metadata:
  name: mysqlserver
  labels:
    app: mysql
spec:
  containers:
    - name: mysqlserver
      image: mysql:latest
      ports:
        - name: mysql-port
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: quarkusdb

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql-service-port
      port: 3306
      targetPort: mysql-port
