apiVersion: v1
kind: Pod
metadata:
  name: chapter5-pod
spec:
  containers:
    - name: chapter5
      image: navkkrnair/chapter5:1.0
      ports:
      - name: chapter5-port
        containerPort: 8080
      env:
        - name: MYSQL_SERVICE_HOST
          value: "mysql-service"
        - name: MYSQL_SERVICE_PORT
          value: "3306"

---

apiVersion: v1
kind: Service
metadata:
  name: chapter5-service
  labels:
    app: chapter5
spec:
  type: LoadBalancer
  selector:
    app: chapter5
  ports:
    - name: service-port
      port: 80
      targetPort: chapter5-port
