apiVersion: apps/v1
kind: Deployment
metadata:
  name: chapter5-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chapter5
  template:
    metadata:
      labels:
        app: chapter5
    spec:
      containers:
        - name: chapter5
          image: navkkrnair/chapter5
          ports:
            - name: chapter5-port
              containerPort: 8080
          env:
            - name: MYSQL_SERVICE_HOST
              value: "mysql-service"
            - name: MYSQL_SERVICE_PORT
              value: "3306"

---

apiVersion: v1
kind: Service
metadata:
  name: chapter5-service
  labels:
    app: chapter5
spec:
  selector:
    app: chapter5
  ports:
    - name: service-port
      port: 80
      targetPort: chapter5-port

---

apiVersion: v1
kind: Pod
metadata:
  name: mysqlserver
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:latest
      ports:
        - name: mysql-port
          containerPort: 3306



---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql-service-port
      port: 3306
      targetPort: mysql-port
