"%dev":
  quarkus:
    datasource:
      db-kind: mysql
      jdbc:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST:localhost}:${MYSQL_SERVICE_PORT:3306}/quarkusdb
        driver: com.mysql.cj.jdbc.Driver
        initial-size: 2
        min-size: 2
        max-size: 8
      username: root
      password: root
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: false

---

"%prod":
  quarkus:
    datasource:
      db-kind: mysql
      jdbc:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST:localhost}:${MYSQL_SERVICE_PORT:3306}/quarkusdb
        driver: com.mysql.cj.jdbc.Driver
        initial-size: 2
        min-size: 2
        max-size: 8
      username: root
      password: root
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: false

---
"%test":
  quarkus:
    datasource:
      db-kind: mysql
      jdbc:
        url: jdbc:mysql://${MYSQL_SERVICE_HOST:localhost}:${MYSQL_SERVICE_PORT:3306}/quarkusdb
        driver: com.mysql.cj.jdbc.Driver
        initial-size: 2
        min-size: 2
        max-size: 8
      username: root
      password: root
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: false
